# Generated by Django 2.2.6 on 2019-10-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191022_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='qual',
            name='points',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_tournaments', to='core.School'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='noty',
            field=models.BooleanField(default=True, help_text='Does this tournament give NOTY points?', verbose_name='NOTY'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='qual',
            field=models.BooleanField(default=True, help_text='Does this tournament give qual points?', verbose_name='QUAL'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='qual_bar',
            field=models.IntegerField(default=0, help_text='If this tournament gives autoquals, this value represents the highest place that receivs the autoqual', verbose_name='Qual Bar'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='soty',
            field=models.BooleanField(default=True, help_text='Does this tournament give SOTY points?', verbose_name='SOTY'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='toty',
            field=models.BooleanField(default=True, help_text='Does this tournament give TOTY points?', verbose_name='TOTY'),
        ),
    ]
