# Generated by Django 2.2.6 on 2019-10-23 17:38

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20191023_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2019, 10, 23, 17, 38, 28, 629673, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="num_debaters",
            field=models.IntegerField(default=-1, verbose_name="Debaters"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="num_novice_teams",
            field=models.IntegerField(default=-1, verbose_name="Novice Teams"),
        ),
    ]
