# Generated by Django 2.2.6 on 2019-10-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20191023_1738"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={"ordering": ("-season", "-date")},
        ),
        migrations.RemoveField(
            model_name="team",
            name="school",
        ),
        migrations.RemoveField(
            model_name="teamresult",
            name="debaters",
        ),
        migrations.AddField(
            model_name="teamresult",
            name="team",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_results",
                to="core.Team",
            ),
            preserve_default=False,
        ),
    ]
