# Generated by Django 2.2.6 on 2019-10-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191024_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noty',
            name='tournament_five',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_five', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='noty',
            name='tournament_four',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_four', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='noty',
            name='tournament_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_one', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='noty',
            name='tournament_six',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_six', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='noty',
            name='tournament_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_three', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='noty',
            name='tournament_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noty_tournament_two', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_five',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_five', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_four',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_four', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_one', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_six',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_six', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_three', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='soty',
            name='tournament_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soty_tournament_two', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_five',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_five', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_four',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_four', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_one', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_six',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_six', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_three', to='core.Tournament'),
        ),
        migrations.AlterField(
            model_name='toty',
            name='tournament_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toty_tournament_two', to='core.Tournament'),
        ),
    ]
