# Generated by Django 2.2.6 on 2019-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20191024_1308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noty",
            options={"ordering": ("-points",)},
        ),
        migrations.AlterModelOptions(
            name="soty",
            options={"ordering": ("-points",)},
        ),
        migrations.AlterModelOptions(
            name="toty",
            options={"ordering": ("-points",)},
        ),
        migrations.AddField(
            model_name="coty",
            name="place",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="noty",
            name="place",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="qual",
            name="place",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="soty",
            name="place",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="toty",
            name="place",
            field=models.IntegerField(default=-1),
        ),
    ]
