# Generated by Django 2.2.6 on 2019-10-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20191024_1359"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toty",
            name="debaters",
        ),
        migrations.AddField(
            model_name="toty",
            name="team",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toty",
                to="core.Team",
            ),
            preserve_default=False,
        ),
    ]
