# Generated by Django 2.2.6 on 2019-10-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191028_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='coty',
            name='tied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noty',
            name='tied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qual',
            name='tied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soty',
            name='tied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toty',
            name='tied',
            field=models.BooleanField(default=False),
        ),
    ]
