# Generated by Django 2.2.6 on 2019-11-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20191106_1546"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField(default=0)),
                (
                    "victor",
                    models.IntegerField(
                        choices=[
                            (0, "UNKNOWN"),
                            (1, "GOV"),
                            (2, "OPP"),
                            (3, "GOV via Forfeit"),
                            (4, "OPP via Forfeit"),
                            (5, "ALL DROP"),
                            (6, "ALL WIN"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "gov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="govs",
                        to="core.Team",
                    ),
                ),
                (
                    "opp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opps",
                        to="core.Team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="core.Tournament",
                    ),
                ),
            ],
        ),
    ]
