# Generated by Django 2.2.6 on 2019-11-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoundStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaks", models.DecimalField(decimal_places=4, max_digits=6)),
                ("ranks", models.DecimalField(decimal_places=4, max_digits=6)),
                ("debater_role", models.CharField(max_length=4, null=True)),
                (
                    "debater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_stats",
                        to="core.Debater",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.Round",
                    ),
                ),
            ],
        ),
    ]
