# Generated by Django 2.2.6 on 2019-11-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20191107_1919"),
        ("core", "0021_roundstats"),
    ]

    operations = []
