# Generated by Django 2.2.6 on 2019-11-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_roundstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolLookup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(max_length=64, unique=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_lookups",
                        to="core.School",
                    ),
                ),
            ],
        ),
    ]
