# Generated by Django 2.2.6 on 2019-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_roundstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='manual_name',
            field=models.CharField(blank=True, help_text='This name will override the autogenerated name', max_length=128),
        ),
    ]
