# Generated by Django 2.2.6 on 2020-03-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_schoollookup"),
        ("core", "0022_tournament_manual_name"),
    ]

    operations = []
