# Generated by Django 2.2.6 on 2019-11-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_merge_20191107_1920"),
        ("core", "0022_tournament_manual_name"),
    ]

    operations = []
