# Generated by Django 2.2.6 on 2019-11-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_schoollookup'),
        ('core', '0023_merge_20191108_1614'),
    ]

    operations = [
    ]
