# Generated by Django 2.2.6 on 2020-03-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20191126_1917'),
        ('core', '0024_video'),
    ]

    operations = [
    ]
