# Generated by Django 3.1.6 on 2021-02-11 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_auto_20200824_2216"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="online_qual_points",
            field=models.BooleanField(
                default=False,
                help_text="Does this tournament give online qual points?",
                verbose_name="Online Qual Points",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="qual_type",
            field=models.IntegerField(
                choices=[
                    (0, "Regular (Points)"),
                    (1, "Brandeis IV"),
                    (2, "Yale IV"),
                    (3, "NorthAms"),
                    (4, "Expansion"),
                    (5, "Worlds"),
                    (6, "NAUDC"),
                    (7, "ProAms"),
                    (8, "Nationals"),
                    (9, "Novice"),
                    (10, "Gender Minority"),
                    (11, "Online No Points"),
                    (12, "Online Points"),
                ],
                default=0,
                verbose_name="Tournament Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.CreateModel(
            name="OnlineQUAL",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("2020", "2020-21"),
                            ("2019", "2019-20"),
                            ("2018", "2018-19"),
                            ("2017", "2017-18"),
                            ("2016", "2016-17"),
                            ("2015", "2015-16"),
                            ("2014", "2014-15"),
                            ("2013", "2013-14"),
                            ("2012", "2012-13"),
                            ("2011", "2011-12"),
                            ("2010", "2010-11"),
                            ("2009", "2009-10"),
                            ("2008", "2008-09"),
                            ("2007", "2007-08"),
                            ("2006", "2006-07"),
                            ("2005", "2005-06"),
                        ],
                        default="2020",
                        max_length=16,
                    ),
                ),
                ("place", models.IntegerField(default=-1)),
                ("points", models.FloatField(default=-1)),
                ("tied", models.BooleanField(default=False)),
                ("marker_one", models.FloatField(default=0)),
                ("marker_two", models.FloatField(default=0)),
                ("marker_three", models.FloatField(default=0)),
                ("marker_four", models.FloatField(default=0)),
                ("marker_five", models.FloatField(default=0)),
                ("marker_six", models.FloatField(default=0)),
                (
                    "debater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual",
                        to="core.debater",
                    ),
                ),
                (
                    "tournament_five",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_five",
                        to="core.tournament",
                    ),
                ),
                (
                    "tournament_four",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_four",
                        to="core.tournament",
                    ),
                ),
                (
                    "tournament_one",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_one",
                        to="core.tournament",
                    ),
                ),
                (
                    "tournament_six",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_six",
                        to="core.tournament",
                    ),
                ),
                (
                    "tournament_three",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_three",
                        to="core.tournament",
                    ),
                ),
                (
                    "tournament_two",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_qual_tournament_two",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ("place",),
                "unique_together": {("season", "debater")},
            },
        ),
    ]
