# Generated by Django 3.1.6 on 2021-11-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20210225_2159"),
        ("core", "0033_merge_20210211_0150"),
    ]

    operations = []
