# Generated by Django 3.1.6 on 2021-11-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_merge_20211116_1654"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("view_accounts_only_video", "View Accounts Only Video"),
                )
            },
        ),
    ]
