# Generated by Django 2.2.6 on 2024-11-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20241126_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerresult",
            name="tie",
            field=models.BooleanField(default=False),
        ),
    ]
