# Generated by Django 2.2.6 on 2024-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_speakerresult_tie"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamresult",
            name="ghost_points",
            field=models.BooleanField(default=False),
        ),
    ]
