# Generated by Django 2.2.6 on 2025-07-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20250302_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTYReaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2025', '2025-26'), ('2024', '2024-25'), ('2023', '2023-24'), ('2022', '2022-23'), ('2021', '2021-22'), ('2020', '2020-21'), ('2019', '2019-20'), ('2018', '2018-19'), ('2017', '2017-18'), ('2016', '2016-17'), ('2015', '2015-16'), ('2014', '2014-15'), ('2013', '2013-14'), ('2012', '2012-13'), ('2011', '2011-12'), ('2010', '2010-11'), ('2009', '2009-10'), ('2008', '2008-09'), ('2007', '2007-08'), ('2006', '2006-07'), ('2005', '2005-06')], default='2024', max_length=16)),
                ('reaff_date', models.DateField()),
                ('new_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toty_reaff_new', to='core.Team')),
                ('old_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toty_reaff_old', to='core.Team')),
            ],
        ),
    ]
