# Generated by Django 2.2.28 on 2025-08-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20250811_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, unique=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
