# Generated by Django 3.2 on 2025-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_qualbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterUniqueTogether(
            name='teamresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teamresult',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, place=-1), fields=('tournament', 'type_of_place', 'place'), name='unique_teamresult_place_when_not_minus_one'),
        ),
    ]
