# Generated by Django 3.2 on 2025-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20250830_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='debater',
            name='first_season',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='debater',
            name='latest_season',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
