# Generated by Django 4.2 on 2025-10-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_schooladmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debater",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
