# Generated by Django 3.2 on 2025-10-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_allow_blank_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebaterAliasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Debater Alias Group',
                'verbose_name_plural': 'Debater Alias Groups',
                'ordering': ('label', 'id'),
            },
        ),
        migrations.AddField(
            model_name='debater',
            name='alias_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debaters', to='core.debateraliasgroup'),
        ),
    ]
