# Generated by Django 4.2 on 2025-10-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_mergedebaterrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergedebaterrequest",
            name="primary_debater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_merge_requests",
                to="core.debater",
            ),
        ),
        migrations.AlterField(
            model_name="mergedebaterrequest",
            name="secondary_debater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_merge_requests",
                to="core.debater",
            ),
        ),
    ]
