# Generated by Django 4.2 on 2025-10-30 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_auto_20251026_1918"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeDebaterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_name", models.CharField(blank=True, max_length=128)),
                ("primary_school_name", models.CharField(blank=True, max_length=128)),
                ("secondary_name", models.CharField(blank=True, max_length=128)),
                ("secondary_school_name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("denial_reason", models.TextField(blank=True)),
                (
                    "primary_debater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_merge_requests",
                        to="core.debater",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_debater_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debater_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondary_debater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secondary_merge_requests",
                        to="core.debater",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="mergedebaterrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("primary_debater", models.F("secondary_debater")), _negated=True
                ),
                name="merge_request_distinct_debaters",
            ),
        ),
    ]
