# Generated by Django 4.2 on 2025-10-30 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_mergedebaterrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debater",
            name="paradigm",
            field=models.URLField(
                blank=True,
                help_text="Link to Google Doc paradigm (must have sharing enabled)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="debater",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who has claimed this debater profile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_debaters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClaimDebaterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("denial_reason", models.TextField(blank=True)),
                (
                    "debater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_requests",
                        to="core.debater",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_claim_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debater_claim_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
