# Generated by Django 4.2 on 2025-10-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_mergedebaterrequest_primary_debater_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergedebaterrequest",
            name="primary_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="mergedebaterrequest",
            name="primary_school_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="mergedebaterrequest",
            name="secondary_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="mergedebaterrequest",
            name="secondary_school_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
