# Generated by Django 4.2 on 2025-11-10 02:40

from django.db import migrations, models


def set_initial_primary(apps, schema_editor):
    SchoolAdmin = apps.get_model("core", "SchoolAdmin")
    school_ids = (
        SchoolAdmin.objects.values_list("school_id", flat=True).distinct()
    )

    for school_id in school_ids:
        admin = (
            SchoolAdmin.objects.filter(school_id=school_id)
            .order_by("created_at", "id")
            .first()
        )
        if admin and not admin.primary:
            SchoolAdmin.objects.filter(id=admin.id).update(primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_debater_paradigm_debater_user_claimdebaterrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooladmin",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_initial_primary, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="schooladmin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("primary", True)),
                fields=("school",),
                name="unique_primary_school_admin",
            ),
        ),
    ]
