# Generated by Django 4.2 on 2025-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_schooladmin_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debater",
            name="dino_judge_contact_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, tournaments know this DINO is open to judging outreach.",
            ),
        ),
        migrations.AddField(
            model_name="debater",
            name="dino_to_contact_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, tournaments know this DINO is open to TO/observer outreach.",
            ),
        ),
        migrations.AlterField(
            model_name="debater",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Varsity"), (0, "Novice"), (2, "Dino")], default=1
            ),
        ),
    ]
