# Generated by Django 4.2 on 2025-11-12 17:23

from django.db import migrations, models


def populate_short_names(apps, schema_editor):
    School = apps.get_model("core", "School")
    Tournament = apps.get_model("core", "Tournament")
    Team = apps.get_model("core", "Team")
    
    # Set short_name to name for all existing records
    for school in School.objects.all():
        school.short_name = school.name
        school.save()
    
    for tournament in Tournament.objects.all():
        tournament.short_name = tournament.name
        tournament.save()
    
    for team in Team.objects.all():
        team.short_name = team.name
        team.save()


def reverse_populate_short_names(apps, schema_editor):
    # No need to do anything on reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_resourcetag_taggedresource_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="short_name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="team",
            name="short_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="tournament",
            name="short_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.RunPython(populate_short_names, reverse_populate_short_names),
    ]
