# Generated by Django 4.2 on 2025-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_resourcetag_taggedresource_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="debater",
            name="region",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional location tags we only show alongside outreach opt-ins.",
            ),
        ),
    ]
