# Generated by Django 4.2 on 2025-12-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_short_name_fields"),
        ("core", "0056_debater_region"),
    ]

    operations = []
