# Generated by Django 4.2 on 2025-12-03 02:30

import json

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_merge_0056_add_short_name_fields_0056_debater_region"),
    ]

    operations = [
      migrations.AddField(
            model_name="debater",
            name="temporary",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="school",
            name="temporary",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
