# Generated by Django 4.2.24 on 2026-03-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_trusted_manual_round_metadata(apps, schema_editor):
    Round = apps.get_model("core", "Round")

    for round_row in Round.objects.select_related("tournament").all():
        import_origin = str(round_row.import_origin or "").strip()
        if import_origin not in {"", "manual"}:
            continue

        metadata = round_row.metadata if isinstance(round_row.metadata, dict) else {}
        metadata.setdefault("record_origin", "trusted_pre_import_manual_round")
        metadata.setdefault("preserved_by_round_import_migration", True)

        update_fields = ["metadata"]
        if not import_origin:
            round_row.import_origin = "manual"
            update_fields.append("import_origin")

        num_rounds = int(getattr(round_row.tournament, "num_rounds", 0) or 0)
        if int(round_row.round_number or 0) > num_rounds and round_row.stage != "outround":
            round_row.stage = "outround"
            update_fields.append("stage")

        round_row.metadata = metadata
        round_row.save(update_fields=sorted(set(update_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_elo_manual_opt_and_pre_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebaterAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(db_index=True, max_length=128)),
                ("normalized_name", models.CharField(db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportedRoundJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=128)),
                ("is_chair", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ImportedRoundMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gov_1_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "PM"),
                            ("MG", "MG"),
                            ("LO", "LO"),
                            ("MO", "MO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "gov_2_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "PM"),
                            ("MG", "MG"),
                            ("LO", "LO"),
                            ("MO", "MO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "opp_1_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "PM"),
                            ("MG", "MG"),
                            ("LO", "LO"),
                            ("MO", "MO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "opp_2_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PM", "PM"),
                            ("MG", "MG"),
                            ("LO", "LO"),
                            ("MO", "MO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("raw_result_code", models.CharField(blank=True, max_length=32)),
                ("raw_outcome_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyntheticResolutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("debater", "Debater"),
                            ("school", "School"),
                            ("team", "Team"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("synthetic_id", models.PositiveIntegerField(db_index=True)),
                ("synthetic_name", models.CharField(blank=True, max_length=255)),
                ("resolved_to_id", models.PositiveIntegerField(db_index=True)),
                ("resolved_to_name", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("source_context", models.JSONField(blank=True, default=dict)),
                ("synthetic_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TournamentImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("file_backup", "File Backup"),
                            ("forum_post", "Forum Post"),
                            ("db_inference", "Inferred From DB"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("original_file_name", models.CharField(blank=True, max_length=255)),
                (
                    "source_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["tournament_id", "-imported_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="debater",
            name="synthetic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[("varsity", "Varsity"), ("novice", "Novice")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="elim_size",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="import_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="import_origin",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="round",
            name="is_rated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="round",
            name="round_label",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="round",
            name="stage",
            field=models.CharField(
                choices=[("prelim", "Prelim"), ("outround", "Outround")],
                db_index=True,
                default="prelim",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="roundstats",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="roundstats",
            name="score_index",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="roundstats",
            name="source_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="school",
            name="synthetic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="synthetic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="qual",
            name="qual_type",
            field=models.IntegerField(
                choices=[
                    (0, "Points"),
                    (1, "Brandeis IV"),
                    (2, "Yale IV"),
                    (3, "NorthAms"),
                    (4, "Expansion"),
                    (5, "Worlds"),
                    (6, "NAUDC"),
                    (7, "ProAms"),
                    (8, "Nationals"),
                    (9, "Novice"),
                    (10, "Gender Minority"),
                    (15, "BIPOC"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="victor",
            field=models.IntegerField(
                choices=[
                    (0, "UNKNOWN"),
                    (1, "GOV"),
                    (2, "OPP"),
                    (3, "GOV via Forfeit"),
                    (4, "OPP via Forfeit"),
                    (5, "ALL DROP"),
                    (6, "ALL WIN"),
                    (7, "BYE"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="roundstats",
            name="debater_role",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="roundstats",
            name="ranks",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roundstats",
            name="speaks",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="qual_type",
            field=models.IntegerField(
                choices=[
                    (0, "Regular (Points)"),
                    (1, "Brandeis IV"),
                    (2, "Yale IV"),
                    (3, "NorthAms"),
                    (4, "Expansion"),
                    (5, "Worlds"),
                    (6, "NAUDC"),
                    (7, "ProAms"),
                    (8, "Nationals"),
                    (9, "Novice"),
                    (10, "Gender Minority"),
                    (15, "BIPOC"),
                    (11, "Online No Points"),
                    (12, "Online Points"),
                    (13, "Online Proams Points"),
                    (14, "Online Gender Minority Points"),
                ],
                default=0,
                verbose_name="Tournament Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                condition=models.Q(("import_key", ""), _negated=True),
                fields=("tournament", "import_key"),
                name="unique_round_import_key_per_tournament",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("stage", "outround"), ("elim_size__isnull", True), _connector="OR"
                ),
                name="round_prelim_requires_null_elim_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("elim_size__isnull", True), ("stage", "outround"), _connector="OR"
                ),
                name="round_elim_size_requires_outround_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("elim_size__isnull", True), ("elim_size__gte", 2), _connector="OR"
                ),
                name="round_elim_size_at_least_two",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundstats",
            constraint=models.UniqueConstraint(
                fields=("round", "debater", "score_index"),
                name="unique_round_stats_score_index",
            ),
        ),
        migrations.AddField(
            model_name="tournamentimport",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_imports",
                to="core.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="tournamentimport",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_imports",
                to="core.tournament",
            ),
        ),
        migrations.AddField(
            model_name="syntheticresolutionlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synthetic_resolution_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="gov_1_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gov_1_round_metadata",
                to="core.debateralias",
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="gov_2_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gov_2_round_metadata",
                to="core.debateralias",
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="opp_1_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opp_1_round_metadata",
                to="core.debateralias",
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="opp_2_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opp_2_round_metadata",
                to="core.debateralias",
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="round",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_metadata",
                to="core.round",
            ),
        ),
        migrations.AddField(
            model_name="importedroundmetadata",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="round_metadata", to="core.tournamentimport"
            ),
        ),
        migrations.AddField(
            model_name="importedroundjudge",
            name="debater_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="judged_rounds",
                to="core.debateralias",
            ),
        ),
        migrations.AddField(
            model_name="importedroundjudge",
            name="round_metadata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judges",
                to="core.importedroundmetadata",
            ),
        ),
        migrations.AddField(
            model_name="debateralias",
            name="debater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="core.debater",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentimport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_hash", ""), _negated=True),
                fields=("tournament", "import_type", "source_hash"),
                name="unique_round_tournament_import_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedroundmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("gov_1_alias__isnull", True),
                    ("gov_2_alias__isnull", True),
                    models.Q(("gov_1_alias", models.F("gov_2_alias")), _negated=True),
                    _connector="OR",
                ),
                name="imported_round_metadata_distinct_gov_aliases",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedroundmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("opp_1_alias__isnull", True),
                    ("opp_2_alias__isnull", True),
                    models.Q(("opp_1_alias", models.F("opp_2_alias")), _negated=True),
                    _connector="OR",
                ),
                name="imported_round_metadata_distinct_opp_aliases",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedroundmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("gov_1_role__isnull", True),
                    ("gov_2_role__isnull", True),
                    models.Q(("gov_1_role", models.F("gov_2_role")), _negated=True),
                    _connector="OR",
                ),
                name="imported_round_metadata_distinct_gov_roles",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedroundmetadata",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("opp_1_role__isnull", True),
                    ("opp_2_role__isnull", True),
                    models.Q(("opp_1_role", models.F("opp_2_role")), _negated=True),
                    _connector="OR",
                ),
                name="imported_round_metadata_distinct_opp_roles",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedroundjudge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_chair", True)),
                fields=("round_metadata",),
                name="unique_round_metadata_chair_judge",
            ),
        ),
        migrations.AddIndex(
            model_name="debateralias",
            index=models.Index(
                fields=["normalized_name", "debater"], name="debater_alias_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="debateralias",
            constraint=models.UniqueConstraint(
                fields=("debater", "source_name"),
                name="unique_debater_alias_source_name",
            ),
        ),
        migrations.RunPython(
            backfill_trusted_manual_round_metadata,
            migrations.RunPython.noop,
        ),
    ]
