# Generated by Django 4.2.24 on 2026-03-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_outround_roundstats_no_speaker_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="is_rated",
        ),
        migrations.RemoveField(
            model_name="round",
            name="weight",
        ),
    ]
