# Generated by Django 4.2 on 2026-08-07 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        ("core", "0069_debater_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Motion text")),
                ("background_slide", models.TextField(blank=True)),
                ("date_set", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="motions",
                        to="core.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_set", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="MotionUserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("ignore", "Ignore")], max_length=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="core.motion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="motionuserstatus",
            constraint=models.UniqueConstraint(
                fields=("user", "motion"), name="unique_user_motion_status"
            ),
        ),
    ]
