# Generated by Django 4.2 on 2026-08-07 16:05

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


def copy_motion_topics(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    MotionTopic = apps.get_model("core", "MotionTopic")
    TaggedMotion = apps.get_model("core", "TaggedMotion")
    Tag = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    motion_type = ContentType.objects.filter(app_label="core", model="motion").first()
    if motion_type is None:
        return

    for old_item in TaggedItem.objects.filter(content_type=motion_type):
        old_tag = Tag.objects.get(pk=old_item.tag_id)
        topic, _ = MotionTopic.objects.get_or_create(
            name=old_tag.name, defaults={"slug": old_tag.slug}
        )
        TaggedMotion.objects.get_or_create(
            content_object_id=old_item.object_id, tag_id=topic.pk
        )


def restore_shared_tags(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    MotionTopic = apps.get_model("core", "MotionTopic")
    TaggedMotion = apps.get_model("core", "TaggedMotion")
    Tag = apps.get_model("taggit", "Tag")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    motion_type = ContentType.objects.filter(app_label="core", model="motion").first()
    if motion_type is None:
        return

    for item in TaggedMotion.objects.all():
        topic = MotionTopic.objects.get(pk=item.tag_id)
        tag, _ = Tag.objects.get_or_create(
            name=topic.name, defaults={"slug": topic.slug}
        )
        TaggedItem.objects.get_or_create(
            content_type=motion_type,
            object_id=item.content_object_id,
            tag_id=tag.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_motion_and_motion_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
            ],
            options={
                "verbose_name": "Motion Topic",
                "verbose_name_plural": "Motion Topics",
            },
        ),
        migrations.CreateModel(
            name="TaggedMotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_motion_items",
                        to="core.motion",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_motion_items",
                        to="core.motiontopic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_motion_topics, restore_shared_tags),
        migrations.AlterField(
            model_name="motion",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="core.TaggedMotion",
                to="core.MotionTopic",
                verbose_name="Tags",
            ),
        ),
    ]
