from django.urls import path

from core.views import (
    admin_audit_views,
    admin_views,
    coty_views,
    debater_export_views,
    debater_views,
    debater_profile_views,
    noty_views,
    results_import_views,
    school_admin_views,
    school_views,
    scheduling_views,
    soty_views,
    elo_views,
    generated_code_views,
    merge_debater_views,
    mittab_bundle_views,
    claim_debater_views,
    team_views,
    toty_views,
    tournament_views,
    video_views,
    motion_views,
    resource_views,
    views,
    plugin_views,
)

app_name = "core"

urlpatterns = [
    path(".well-known/ai-plugin.json", plugin_views.ai_plugin_manifest, name="ai_plugin_manifest"),
    path(".well-known/openapi.json", plugin_views.PluginSchemaView.as_view(), name="openapi_schema"),
    path("", views.index, name="index"),
    path(
        "core/generated-codes/",
        generated_code_views.GeneratedCodeView.as_view(),
        name="generated_code",
    ),
    path("standings/replay/", views.standings_replay, name="standings_replay"),
    path("stats/", views.stats, name="stats"),
    path("core/schools/", school_views.SchoolListView.as_view(), name="school_list"),
    path(
        "core/schools/<int:pk>",
        school_views.SchoolDetailView.as_view(),
        name="school_detail",
    ),
    path(
        "core/schools/<int:pk>/edit",
        school_views.SchoolUpdateView.as_view(),
        name="school_update",
    ),
    path(
        "core/schools/<int:pk>/delete",
        school_views.SchoolDeleteView.as_view(),
        name="school_delete",
    ),
    path(
        "core/schools/create",
        school_views.SchoolCreateView.as_view(),
        name="school_create",
    ),
    path(
        "core/schools/autocomplete",
        school_views.SchoolAutocomplete.as_view(),
        name="school_autocomplete",
    ),
    path(
        "core/schools/autocomplete/claim",
        school_views.ClaimSchoolAutocomplete.as_view(),
        name="claim_school_autocomplete",
    ),
    path(
        "core/debaters/", debater_views.DebaterListView.as_view(), name="debater_list"
    ),
    path(
        "core/dino-judges/",
        debater_views.DinoJudgeListView.as_view(),
        name="judge_list",
    ),
    path(
        "core/dino-tos/",
        debater_views.DinoTOListView.as_view(),
        name="to_list",
    ),
    path(
        "core/debaters/<int:pk>",
        debater_views.DebaterDetailView.as_view(),
        name="debater_detail",
    ),
    path(
        "core/debaters/<int:pk>/tab-cards-csv",
        debater_export_views.debater_tab_cards_csv,
        name="debater_tab_cards_csv",
    ),
    path(
        "core/debaters/<int:pk>/edit",
        debater_views.DebaterUpdateView.as_view(),
        name="debater_update",
    ),
    path(
        "core/debaters/<int:pk>/delete",
        debater_views.DebaterDeleteView.as_view(),
        name="debater_delete",
    ),
    path(
        "core/debaters/create",
        debater_views.DebaterCreateView.as_view(),
        name="debater_create",
    ),
    path(
        "core/debaters/autocomplete",
        debater_views.DebaterAutocomplete.as_view(),
        name="debater_autocomplete",
    ),
    path(
        "core/debater-alias-groups/autocomplete",
        debater_views.DebaterAliasGroupAutocomplete.as_view(),
        name="alias_group_autocomplete",
    ),
    path("core/teams/", team_views.TeamListView.as_view(), name="team_list"),
    path(
        "core/teams/<int:pk>", team_views.TeamDetailView.as_view(), name="team_detail"
    ),
    path(
        "core/teams/<int:pk>/edit",
        team_views.TeamUpdateView.as_view(),
        name="team_update",
    ),
    path(
        "core/teams/<int:pk>/delete",
        team_views.TeamDeleteView.as_view(),
        name="team_delete",
    ),
    path(
        "core/teams/autocomplete",
        team_views.TeamAutocomplete.as_view(),
        name="team_autocomplete",
    ),
    path("core/videos/", video_views.VideoListView.as_view(), name="video_list"),
    path("core/motions/", motion_views.MotionListView.as_view(), name="motion_list"),
    path("core/motions/random", motion_views.MotionRandomView.as_view(), name="motion_random"),
    path("core/motions/create", motion_views.MotionCreateView.as_view(), name="motion_create"),
    path("core/motions/import", motion_views.MotionImportView.as_view(), name="motion_import"),
    path("core/motions/<int:pk>", motion_views.MotionDetailView.as_view(), name="motion_detail"),
    path("core/motions/<int:pk>/edit", motion_views.MotionUpdateView.as_view(), name="motion_update"),
    path("core/motions/<int:pk>/status", motion_views.MotionStatusView.as_view(), name="motion_status"),
    path(
        "core/motions/topics",
        motion_views.MotionTopicAutocomplete.as_view(create_field="name"),
        name="motion_topic_autocomplete",
    ),
    path(
        "core/motions/topics_no_create",
        motion_views.MotionTopicAutocomplete.as_view(),
        name="motion_topic_autocomplete_no_create",
    ),
    path("core/videos/random", video_views.VideoRandomView.as_view(), name="video_random"),
    path(
        "core/videos/<int:pk>",
        video_views.VideoDetailView.as_view(),
        name="video_detail",
    ),
    path(
        "core/videos/<int:pk>/edit",
        video_views.VideoUpdateView.as_view(),
        name="video_update",
    ),
    path(
        "core/videos/<int:pk>/delete",
        video_views.VideoDeleteView.as_view(),
        name="video_delete",
    ),
    path(
        "core/videos/create", video_views.VideoCreateView.as_view(), name="video_create"
    ),
    path(
        "core/videos/tags",
        video_views.TagAutocomplete.as_view(create_field="name"),
        name="tag_autocomplete",
    ),
    path(
        "core/videos/tags_no_create",
        video_views.TagAutocomplete.as_view(),
        name="tag_autocomplete_no_create",
    ),
    path(
        "core/videos/tags/<str:slug>",
        video_views.TagDetail.as_view(),
        name="tag_detail",
    ),
    # Resource URLs
    path("core/resources/", resource_views.ResourceListView.as_view(), name="resource_list"),
    path(
        "core/resources/<int:pk>",
        resource_views.ResourceDetailView.as_view(),
        name="resource_detail",
    ),
    path(
        "core/resources/<int:pk>/edit",
        resource_views.ResourceUpdateView.as_view(),
        name="resource_update",
    ),
    path(
        "core/resources/<int:pk>/delete",
        resource_views.ResourceDeleteView.as_view(),
        name="resource_delete",
    ),
    path(
        "core/resources/create",
        resource_views.ResourceCreateView.as_view(),
        name="resource_create"
    ),
    path(
        "core/resources/my-resources",
        resource_views.MyResourcesView.as_view(),
        name="my_resources"
    ),
    path(
        "core/resources/tags",
        resource_views.ResourceTagAutocomplete.as_view(create_field="name"),
        name="resource_tag_autocomplete",
    ),
    path(
        "core/resources/tags_no_create",
        resource_views.ResourceTagAutocomplete.as_view(),
        name="resource_tag_autocomplete_no_create",
    ),
    path(
        "core/resources/tags/<str:slug>",
        resource_views.ResourceTagDetail.as_view(),
        name="resource_tag_detail",
    ),
    path(
        "core/tournaments/",
        tournament_views.TournamentListView.as_view(),
        name="tournament_list",
    ),
    path(
        "core/schedules/", tournament_views.ScheduleView.as_view(), name="schedule_view"
    ),
    path(
        "core/tournaments/<int:pk>",
        tournament_views.TournamentDetailView.as_view(),
        name="tournament_detail",
    ),
    path(
        "core/tournaments/<int:pk>/edit",
        tournament_views.TournamentUpdateView.as_view(),
        name="tournament_update",
    ),
    path(
        "core/tournaments/<int:pk>/delete",
        tournament_views.TournamentDeleteView.as_view(),
        name="tournament_delete",
    ),
    path(
        "core/tournaments/create",
        tournament_views.TournamentCreateView.as_view(),
        name="tournament_create",
    ),
    path(
        "core/tournaments/autocomplete",
        tournament_views.TournamentAutocomplete.as_view(),
        name="tournament_autocomplete",
    ),
    path(
        "core/tournaments/all_autocomplete",
        tournament_views.AllTournamentAutocomplete.as_view(),
        name="all_tournament_autocomplete",
    ),
    path(
        "core/widgets/recent-results/",
        tournament_views.RecentResultsWidgetView.as_view(),
        name="recent_results_widget",
    ),
    path(
        "core/tournaments/data_entry/setup",
        results_import_views.TournamentDataEntrySetupView.as_view(),
        name="tournament_dataentry_setup",
    ),
    path(
        "core/tournaments/data_entry",
        results_import_views.TournamentDataEntryView.as_view(),
        name="tournament_dataentry",
    ),
    path(
        "core/tournaments/mittab_bundle/upload",
        mittab_bundle_views.TournamentMittabBundleUploadView.as_view(),
        name="tournament_mittab_bundle_upload",
    ),
    path(
        "core/tournaments/get_new_form",
        results_import_views.get_new_team_form,
        name="get_new_team_form",
    ),
    path("core/soty", soty_views.SOTYListView.as_view(), name="soty"),
    path("core/toty", toty_views.TOTYListView.as_view(), name="toty"),
    path("core/noty", noty_views.NOTYListView.as_view(), name="noty"),
    path("core/coty", coty_views.COTYListView.as_view(), name="coty"),
    path("core/elo/", elo_views.elo_dashboard, name="elo_dashboard"),
    path("core/admin-tools/", admin_views.AdminToolsView.as_view(), name="admin_tools"),
    path(
        "core/admin/synthetic-cleanup/",
        admin_views.SyntheticCleanupView.as_view(),
        name="synthetic_cleanup",
    ),
    path(
        "core/admin/scheduling/",
        scheduling_views.SchedulingDashboardView.as_view(),
        name="scheduling_dashboard",
    ),
    path(
        "core/admin/scheduling/workspace-data/",
        scheduling_views.SchedulingWorkspaceDataView.as_view(),
        name="scheduling_workspace_data",
    ),
    path(
        "core/admin/scheduling/save-browser-run/",
        scheduling_views.SchedulingBrowserRunSaveView.as_view(),
        name="scheduling_save_browser_run",
    ),
    path(
        "core/admin/scheduling/download/<str:kind>/",
        scheduling_views.SchedulingWorkspaceCSVDownloadView.as_view(),
        name="scheduling_download_csv",
    ),
    path(
        "core/admin/scheduling/runs/<int:pk>/output/",
        scheduling_views.SchedulingRunOutputDownloadView.as_view(),
        name="scheduling_run_output",
    ),
    path(
        "core/admin/synthetic-resolve/",
        admin_views.SyntheticResolutionView.as_view(),
        name="synthetic_resolution",
    ),
    path(
        "core/admin/elo-cache/invalidate/",
        admin_views.EloCacheInvalidateView.as_view(),
        name="invalidate_elo_cache",
    ),
    path(
        "core/admin/round-amendments/",
        admin_views.RoundAmendmentUploadView.as_view(),
        name="round_amendments_upload",
    ),
    path(
        "core/admin/tournament-pipeline-audit/",
        admin_audit_views.ConsolidatedTournamentAuditView.as_view(),
        name="tournament_pipeline_audit",
    ),
    path(
        "core/admin/tournament-audit/<int:pk>/",
        admin_audit_views.TournamentAuditDetailView.as_view(),
        name="tournament_audit_detail",
    ),
    path(
        "core/admin/tournament-audit/<int:tournament_id>/round/new/",
        admin_audit_views.TournamentAuditRoundEditView.as_view(),
        name="tournament_audit_round_create",
    ),
    path(
        "core/admin/tournament-audit/<int:tournament_id>/round/<int:round_id>/",
        admin_audit_views.TournamentAuditRoundEditView.as_view(),
        name="tournament_audit_round_edit",
    ),
    path(
        "core/admin/tournament-audit/<int:tournament_id>/round/<int:round_id>/delete/",
        admin_audit_views.TournamentAuditRoundDeleteView.as_view(),
        name="tournament_audit_round_delete",
    ),
    path(
        "core/admin/tournament-audit/<int:tournament_id>/imports/<int:import_id>/delete/",
        admin_audit_views.TournamentImportDeleteView.as_view(),
        name="tournament_import_delete",
    ),
    path(
        "core/admin/tournament-audit/<int:tournament_id>/imports/<int:import_id>/move/",
        admin_audit_views.TournamentImportMoveView.as_view(),
        name="tournament_import_move",
    ),
    path(
        "core/mittab-dashboard/",
        admin_views.MitTabDashboardView.as_view(),
        name="mittab_dashboard",
    ),
    path(
        "core/rankings-recompute/",
        admin_views.RankingsRecomputeView.as_view(),
        name="rankings_recompute",
    ),
    path(
        "core/admin/debater-aliases/",
        admin_views.DebaterAliasSuggestionView.as_view(),
        name="debater_alias_suggestions",
    ),
    path(
        "core/admin/school-short-names/",
        admin_views.SchoolShortNameAuditView.as_view(),
        name="school_short_name_audit",
    ),
    path(
        "core/admin/merge-suggestions/",
        admin_views.MergeSuggestionsView.as_view(),
        name="merge_suggestions",
    ),
    path(
        "core/admin/synthetic-resolution-suggestions/",
        admin_views.SyntheticResolutionSuggestionsView.as_view(),
        name="synthetic_resolution_suggestions",
    ),
    path(
        "core/school-admin/",
        school_admin_views.SchoolAdminDashboardView.as_view(),
        name="school_admin_dashboard",
    ),
    path(
        "core/school-admin/<int:school_id>/debaters/",
        school_admin_views.SchoolAdminDebaterListView.as_view(),
        name="school_admin_debater_list",
    ),
    path(
        "core/school-admin/debater/<int:pk>/edit/",
        school_admin_views.SchoolAdminDebaterUpdateView.as_view(),
        name="school_admin_debater_update",
    ),
    path(
        "core/school-admin/<int:school_id>/debater/create/",
        school_admin_views.SchoolAdminDebaterCreateView.as_view(),
        name="school_admin_debater_create",
    ),
    path(
        "core/manage-school-admins/",
        school_admin_views.SuperuserSchoolAdminManagementView.as_view(),
        name="manage_school_admins",
    ),
    path(
        "core/manage-school-admins/add/",
        school_admin_views.SchoolAdminAddView.as_view(),
        name="school_admin_add",
    ),
    path(
        "core/manage-school-admins/remove/",
        school_admin_views.SchoolAdminRemoveView.as_view(),
        name="school_admin_remove",
    ),
    path(
        "core/manage-school-admins/primary/",
        school_admin_views.SchoolAdminPrimaryUpdateView.as_view(),
        name="school_admin_set_primary",
    ),
    path(
        "core/merge-debaters/request/",
        merge_debater_views.MergeDebaterRequestCreateView.as_view(),
        name="merge_debater_request_create",
    ),
    path(
        "core/merge-debaters/review/",
        merge_debater_views.MergeDebaterRequestReviewView.as_view(),
        name="merge_debater_request_review",
    ),
    path(
        "core/my-profile/",
        debater_profile_views.MyDebaterProfileView.as_view(),
        name="my_debater_profile",
    ),
    path(
        "core/claim-debater/request/",
        claim_debater_views.ClaimDebaterRequestCreateView.as_view(),
        name="claim_debater_request_create",
    ),
    path(
        "core/debaters/autocomplete/merge",
        merge_debater_views.MergeDebaterAutocompleteView.as_view(),
        name="merge_debater_autocomplete",
    ),
    path(
        "core/claim-debater/review/",
        claim_debater_views.ClaimDebaterRequestReviewView.as_view(),
        name="claim_debater_request_review",
    ),
    path(
        "core/debater/<int:pk>/edit-profile/",
        claim_debater_views.DebaterProfileEditView.as_view(),
        name="debater_profile_edit",
    ),
    path(
        "core/user-autocomplete/",
        school_admin_views.UserAutocompleteView.as_view(),
        name="user_autocomplete",
    ),
]
